### ISSUE TITLE
Indexing fails if username cotains a dot

### ISSUE THREAD

**Issue by Norghul** [nextcloud/fulltextsearch_elasticsearch#18] opened 2018-03-23 08:04 UTC
Hi,

we have a setup, where the usernames (can) contain dots... Now indexing the OC leads to the following error - since ES uses the dot as object separator...

Let's say we have a user _example_ and another user _example.user_ 

`  [Elasticsearch\Common\Exceptions\BadRequest400Exception]
  {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Could not dynamically add mapping for field [example.user]. Existing mapping
   for [share_names.example] must be of type object but found [text]."}],"type":"mapper_parsing_exception","reason":"Could not dynamically add mapping for
  field [example.user]. Existing mapping for [share_names.example] must be of type object but found [text]."},"status":400}`

The corresponding exception in ES:

`[DEBUG][o.e.a.b.TransportShardBulkAction] [Vm52UFU] [cloud_index][2] failed to execute bulk item (index) BulkShardRequest [[cloud_index][2]] containing [index {[cloud_index][standard][files:4763], source[{"share_names":{"example.user":"documents"},"owner":"example.user","users":[],"groups":[],"circles":[],"tags":["local"],"provider":"files","title":"documents"}]}]
org.elasticsearch.index.mapper.MapperParsingException: Could not dynamically add mapping for field [example.user]. Existing mapping for [share_names.example] must be of type object but found [text].
        at org.elasticsearch.index.mapper.DocumentParser.getDynamicParentMapper(DocumentParser.java:876) ~
[...]`

So I think there needs to be some kind of escaping of the dot in an username, to make this work...

**Comment by daita** [comment] 2018-05-14 10:55
Should be fixed in 0.7

**Comment by joergmschulz** [comment] 2018-05-14 15:34
confirmed - files of my .dot. users can now be indexed.

**Comment by daita** [comment] 2018-05-14 18:36
@Norghul - please confirm and close this issue if it is fixed

**Closed** 2018-06-14 10:41 UTC
Labels: bug, fixed ?

**Comment by ihasdivui** [comment] 2020-01-27 17:04
I just spent some time writing about seperate issue because I just encountered something similar, only then stumbled upon this. `<Speculation without any proof>` I assume while fixing this issue, this bug might have actually been introduced `</Speculation without any proof>`

I can't index most files on a certain Nextcloud instance, due to a user owning said files having a dot in their username.
Nextcloud 18.0.0, Elasticsearch 7.5.

Full text search 1.4.0
Full text search - Elasticsearch Platform 1.5.0
Full text search - Files 1.4.1

The full (anonymized) exception that happens on indexing any files accessible by a particular user, 
`Name X.`, is:

```
java.lang.IllegalArgumentException: Can't merge a non object mapping [share_names.Name X\] with an object mapping [share_names.Name X\]
```

As you can see in the exception alone, there seems to be a falsely escaped dot character.

Here is an object (again, anonymized) that I gathered from the Elasticsearch logs:

```
  {
    share_names: {
      'Name X\\.': 'Path/to/a/file.ai',
      aname: 'Path/to/a/file.ai',
      'anothername2': 'Path/to/a/file.ai',
      anothername3: 'Path/to/a/file.ai',
      'anothername4': 'Path/to/a/file.ai',
      anothername5: 'Path/to/a/file.ai',
      anothername6: 'Path/to/a/file.ai',
      anothername7: 'Path/to/a/file.ai',
      anothername8: 'Path/to/a/file.ai',
      anothername9: 'Path/to/a/file.ai',
      'anothername10': 'Path/to/a/file.ai',
      anothername11: 'Path/to/a/file.ai',
      anothername12: 'Path/to/a/file.ai',
      anothername13: 'Path/to/a/file.ai',
      'anothername14': 'Path/to/a/file.ai',
      anothername15: 'Path/to/a/file.ai',
      anothername16: 'Path/to/a/file.ai',
      'anothername17': 'Path/to/a/file.ai'
    },
    owner: 'Name X.',
    users: [],
    groups: [ 'agroup' ],
    circles: [],
    links: [],
    metatags: [ 'files_local' ],
    subtags: [],
    tags: [],
    hash: '',
    provider: 'files',
    source: 'files_local',
    title: 'Path/to/a/file.ai',
    parts: { comments: '' },
    content: ''
  }
```

As can be seen above, the name there is
`Name X\\.` in the share name, while the owner name is just
`Name X.`.

This strongly indicates some kind of character escaping issue to me.
