### ISSUE TITLE
GroupFolder Indexing Issue!

### ISSUE THREAD

**Issue by j03h** [nextcloud/fulltextsearch_elasticsearch#21] opened 2018-05-05 19:26 UTC
Im trying to index with ElasticSearch the content of GroupFolder.

Every is fine, but the index is created only for the first user in the user group allowed to interact with this GroupFolder.

The rest of users cant search inside the index because the index is not ceated for him!

Index External Drives is activated.

**Comment by daita** [comment] 2018-05-14 10:57
Should be fixed in 0.7

**Comment by joergmschulz** [comment] 2018-05-14 15:33
Just deleted the three folders and reinstalled from the AppStore.

php ../occ app:list |grep fullt
  - files_fulltextsearch: 0.7.0
  - fulltextsearch: 0.7.0
  - fulltextsearch_elasticsearch: 0.7.0

php ../occ fulltextsearch:index
(many successful messages)

Files are indexed and found for
- users with DOT in the names

but: 
Groupfolders are not (yet) indexed.

**Comment by daita** [comment] 2018-05-14 18:37
Please confirm that the option is enabled in the Settings for Full text search / Files.

If the index is over and you can't find those files, can you give me more details on the configuration of your group folders ?

**Comment by joergmschulz** [comment] 2018-05-14 18:50
as we live on my test server, index is quite fast ;-)
The situation is reproducible.

- Open Document files are indexed alright when they live OUTSIDE a group folder.
- Text Document files are indexed alright regardless of their location (.txt and .md files alike)

So what questions would you have regarding the groupfolders configuration? Access should be possible as proved by the fact that text documents are indexed. 

Nextcloud log says: 
`Invalid argument supplied for foreach() at /var/www/nc/apps/files_fulltextsearch/lib/Service/ConfigService.php#253
array_keys() expects parameter 1 to be array, null given at /var/www/nc/apps/files_fulltextsearch/lib/Service/ConfigService.php#252`

The Folder name contains a blank while the filenames are normal. Will create another shared folder with a decent name.

**Comment by daita** [comment] 2018-05-14 20:43
Thanks for this nice report !

**Comment by daita** [comment] 2018-05-15 10:59
@joergmschulz Unfortunatly, I am not able to reproduce this issue. For me, your document is indexed while in the local filesystem, and in a groupfolders.

Also, all groups that are linked to a groupfolders are indexed in elasticsearch.

Can you provide any specific details on the setup of the groupfolders app ? For exemple:

- Is the file shared to any user out of the group, 
- do you have user that are never logged in to your nextcloud in those groups.

However, I have found a bug that keep indexing the same file each time you're calling an index. This should be fixed next release.

**Comment by daita** [comment] 2018-05-15 11:00
Note that this PHP error is strange, are you sure you did reset your index after upgrading to 0.7.x ?

**Comment by joergmschulz** [comment] 2018-05-15 11:48
Hello, 
yes, this is the case: as it is test, most (LDAP) users have never logged in.

I don’t have additional shares, no.


And: After deleting the index, the mentioned PHP error is gone. 
But still - no pdf and odt files found in the GroupFolder.


> Am 15.05.2018 um 12:59 schrieb Maxence Lange <notifications@github.com>:
> 
> do you have user that are never logged in to your nextcloud in those groups.

**Comment by daita** [comment] 2018-05-15 11:55
Can you make a test with a groupfolder including only with users you are sure they already logged in ?

**Comment by daita** [comment] 2018-05-15 11:56
(I think the PHP error is from an old index pre-0.7.x)

**Comment by joergmschulz** [comment] 2018-05-17 07:41
one more reinstall, one more index reset - and now everything works fine. Thank you for fixing!

**Comment by daita** [comment] 2018-05-17 10:26
@j03h what about you ? can we close this report ?

**Closed** 2018-06-14 10:40 UTC
Labels: fixed ?
